//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LINE 47")]
        public string FormTittle {
            get {
                return ((string)(this["FormTittle"]));
            }
            set {
                this["FormTittle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PH")]
        public string PLANT_BD_CD {
            get {
                return ((string)(this["PLANT_BD_CD"]));
            }
            set {
                this["PLANT_BD_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPS,UPC,FGA,FSS")]
        public string OP_GROUP {
            get {
                return ((string)(this["OP_GROUP"]));
            }
            set {
                this["OP_GROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("047,048")]
        public string LINE_CD {
            get {
                return ((string)(this["LINE_CD"]));
            }
            set {
                this["LINE_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string ROW_HEIGHT {
            get {
                return ((string)(this["ROW_HEIGHT"]));
            }
            set {
                this["ROW_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal TIMER_ANDON {
            get {
                return ((decimal)(this["TIMER_ANDON"]));
            }
            set {
                this["TIMER_ANDON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string DIRECT_GATE_YN {
            get {
                return ((string)(this["DIRECT_GATE_YN"]));
            }
            set {
                this["DIRECT_GATE_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string GATE_COM {
            get {
                return ((string)(this["GATE_COM"]));
            }
            set {
                this["GATE_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int GATE_BAUDRATE {
            get {
                return ((int)(this["GATE_BAUDRATE"]));
            }
            set {
                this["GATE_BAUDRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string GATE_SERVER_SOCKET_YN {
            get {
                return ((string)(this["GATE_SERVER_SOCKET_YN"]));
            }
            set {
                this["GATE_SERVER_SOCKET_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User Id=LMES;Password=LMES;Server=10.10.100.10;Direct=True;Sid=LMES")]
        public string DIRECT_CONNECTION {
            get {
                return ((string)(this["DIRECT_CONNECTION"]));
            }
            set {
                this["DIRECT_CONNECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string DIRECT_CONNECT_YN {
            get {
                return ((string)(this["DIRECT_CONNECT_YN"]));
            }
            set {
                this["DIRECT_CONNECT_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string SWITCH_FORM_YN {
            get {
                return ((string)(this["SWITCH_FORM_YN"]));
            }
            set {
                this["SWITCH_FORM_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SWITCH_TIMER {
            get {
                return ((int)(this["SWITCH_TIMER"]));
            }
            set {
                this["SWITCH_TIMER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string SOUND_YN {
            get {
                return ((string)(this["SOUND_YN"]));
            }
            set {
                this["SOUND_YN"] = value;
            }
        }
    }
}
